<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.1.103</Version>
    <AssemblyVersion>1.1.103</AssemblyVersion>
    <FileVersion>1.1.103</FileVersion>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)valheim.targets" />
</Project>
